In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv('/Users/shivendragupta/Desktop/Machine Learning/Feature Engineering/credit_data.csv')

In [24]:
df.head()

,Customer_ID,Total_Account_Balance,Total_Credit_Limit,Late_Payments,Total_Payments,Accounts_Opened_Last_12_Months,Total_Accounts,Accounts_30Plus_Days_Late,Debt_to_Credit_Ratio,Late_Payment_Ratio,Recent_Credit_Opening_Ratio,Delinquency_Rate
0,1,16795,32446,0,110,0,3,3,0.517629,0.000000,0.000000,1.000000
1,2,1860,18046,2,182,0,12,2,0.103070,0.010989,0.000000,0.166667
2,3,39158,29818,7,52,1,7,1,1.313234,0.134615,0.142857,0.142857
3,4,45732,9324,3,144,4,7,2,4.904762,0.020833,0.571429,0.285714
4,5,12284,81323,15,35,0,10,3,0.151052,0.428571,0.000000,0.300000

In [25]:
df = df.drop(columns=['Debt_to_Credit_Ratio','Late_Payment_Ratio','Recent_Credit_Opening_Ratio','Delinquency_Rate'])

# 1. Debt-to-credit Ratio

## This measures the amount of credit you're using compared to your total available credit limit.

 ## Debt-credit-ratio = Total Account Balance / Total Credit Limit.

In [26]:
df['Debt_cred_ratio'] = df['Total_Account_Balance']/df['Total_Credit_Limit']
df.head()

,Customer_ID,Total_Account_Balance,Total_Credit_Limit,Late_Payments,Total_Payments,Accounts_Opened_Last_12_Months,Total_Accounts,Accounts_30Plus_Days_Late,Debt_cred_ratio
0,1,16795,32446,0,110,0,3,3,0.517629
1,2,1860,18046,2,182,0,12,2,0.103070
2,3,39158,29818,7,52,1,7,1,1.313234
3,4,45732,9324,3,144,4,7,2,4.904762
4,5,12284,81323,15,35,0,10,3,0.151052

### High ratio indicates high reliance of credit limit and a risky behavior

# 2. Late Payment Ratio

## This measures the frequency of late payments relative to the total number of payments due.

## Late Payment Ratio = Late Payments / Total Payments.

In [27]:
df['late_payment_ratio'] = df['Late_Payments'] / df['Total_Payments']
df.head()

,Customer_ID,Total_Account_Balance,Total_Credit_Limit,Late_Payments,Total_Payments,Accounts_Opened_Last_12_Months,Total_Accounts,Accounts_30Plus_Days_Late,Debt_cred_ratio,late_payment_ratio
0,1,16795,32446,0,110,0,3,3,0.517629,0.000000
1,2,1860,18046,2,182,0,12,2,0.103070,0.010989
2,3,39158,29818,7,52,1,7,1,1.313234,0.134615
3,4,45732,9324,3,144,4,7,2,4.904762,0.020833
4,5,12284,81323,15,35,0,10,3,0.151052,0.428571

### A higher ratio indicates that more late payments that indicates irresponsible or risky behaviour

# 3. Recent Credit Opening Ratio

## Recent_credit_opening_ratio = Accounts Opened Last 12 Months / Total Accounts

## This measures the proportion of credit accounts opended in last 12 months relative to total credit accounts

In [28]:
df['Recent_credit_opening_ratio'] = df['Accounts_Opened_Last_12_Months']/df['Total_Accounts']
df.head()

,Customer_ID,Total_Account_Balance,Total_Credit_Limit,Late_Payments,Total_Payments,Accounts_Opened_Last_12_Months,Total_Accounts,Accounts_30Plus_Days_Late,Debt_cred_ratio,late_payment_ratio,Recent_credit_opening_ratio
0,1,16795,32446,0,110,0,3,3,0.517629,0.000000,0.000000
1,2,1860,18046,2,182,0,12,2,0.103070,0.010989,0.000000
2,3,39158,29818,7,52,1,7,1,1.313234,0.134615,0.142857
3,4,45732,9324,3,144,4,7,2,4.904762,0.020833,0.571429
4,5,12284,81323,15,35,0,10,3,0.151052,0.428571,0.000000

### Higher value indicates that over reliance on credit indicating financial instability

# 4. Delinquency Rate

## Deliquency_rate  = Accounts 30+ Days Late / Total Accounts.

## This measures the ratio of accounts with late payment past 30 days to the total accounts

In [29]:
df['Deliquency_rate'] = df['Accounts_30Plus_Days_Late']/df['Total_Accounts']
df.head()

,Customer_ID,Total_Account_Balance,Total_Credit_Limit,Late_Payments,Total_Payments,Accounts_Opened_Last_12_Months,Total_Accounts,Accounts_30Plus_Days_Late,Debt_cred_ratio,late_payment_ratio,Recent_credit_opening_ratio,Deliquency_rate
0,1,16795,32446,0,110,0,3,3,0.517629,0.000000,0.000000,1.000000
1,2,1860,18046,2,182,0,12,2,0.103070,0.010989,0.000000,0.166667
2,3,39158,29818,7,52,1,7,1,1.313234,0.134615,0.142857,0.142857
3,4,45732,9324,3,144,4,7,2,4.904762,0.020833,0.571429,0.285714
4,5,12284,81323,15,35,0,10,3,0.151052,0.428571,0.000000,0.300000

### A higher delinquency rate indicate higher chances of payment defaults in future

# 5. Credit Health Score

## Credit Health Score=Credit Utilization Ratio+Late Payment Ratio+Delinquency Rate

In [33]:
df['Credit_health_score'] = df['Debt_cred_ratio'] + df['late_payment_ratio'] + df['Deliquency_rate']
df.head()

,Customer_ID,Total_Account_Balance,Total_Credit_Limit,Late_Payments,Total_Payments,Accounts_Opened_Last_12_Months,Total_Accounts,Accounts_30Plus_Days_Late,Debt_cred_ratio,late_payment_ratio,Recent_credit_opening_ratio,Deliquency_rate,Credit_health_score
0,1,16795,32446,0,110,0,3,3,0.517629,0.000000,0.000000,1.000000,1.517629
1,2,1860,18046,2,182,0,12,2,0.103070,0.010989,0.000000,0.166667,0.280726
2,3,39158,29818,7,52,1,7,1,1.313234,0.134615,0.142857,0.142857,1.590706
3,4,45732,9324,3,144,4,7,2,4.904762,0.020833,0.571429,0.285714,5.211310
4,5,12284,81323,15,35,0,10,3,0.151052,0.428571,0.000000,0.300000,0.879623

### Lower the value better is the credit worthiness

# 6. Average Balance per Account

## Indicates amount of account balance per account

## Total_Account_Balance / Total_Accounts

In [34]:
df['Average_balance_per_account'] = df['Total_Account_Balance']/df['Total_Accounts']
df.head()

,Customer_ID,Total_Account_Balance,Total_Credit_Limit,Late_Payments,Total_Payments,Accounts_Opened_Last_12_Months,Total_Accounts,Accounts_30Plus_Days_Late,Debt_cred_ratio,late_payment_ratio,Recent_credit_opening_ratio,Deliquency_rate,Credit_health_score,Average_balance_per_account
0,1,16795,32446,0,110,0,3,3,0.517629,0.000000,0.000000,1.000000,1.517629,5598.333333
1,2,1860,18046,2,182,0,12,2,0.103070,0.010989,0.000000,0.166667,0.280726,155.000000
2,3,39158,29818,7,52,1,7,1,1.313234,0.134615,0.142857,0.142857,1.590706,5594.000000
3,4,45732,9324,3,144,4,7,2,4.904762,0.020833,0.571429,0.285714,5.211310,6533.142857
4,5,12284,81323,15,35,0,10,3,0.151052,0.428571,0.000000,0.300000,0.879623,1228.400000

### A higher average account balance indicated higher reliance on credit

# 7. Average Credit Limit per Account

## This measures the average credit utilization per account.

## Total_Credit_Limit / Total_Accounts

In [35]:
df['Average_credit_limit_per_account'] = df['Total_Credit_Limit']/df['Total_Accounts']
df.head()

,Customer_ID,Total_Account_Balance,Total_Credit_Limit,Late_Payments,Total_Payments,Accounts_Opened_Last_12_Months,Total_Accounts,Accounts_30Plus_Days_Late,Debt_cred_ratio,late_payment_ratio,Recent_credit_opening_ratio,Deliquency_rate,Credit_health_score,Average_balance_per_account,Average_credit_limit_per_account
0,1,16795,32446,0,110,0,3,3,0.517629,0.000000,0.000000,1.000000,1.517629,5598.333333,10815.333333
1,2,1860,18046,2,182,0,12,2,0.103070,0.010989,0.000000,0.166667,0.280726,155.000000,1503.833333
2,3,39158,29818,7,52,1,7,1,1.313234,0.134615,0.142857,0.142857,1.590706,5594.000000,4259.714286
3,4,45732,9324,3,144,4,7,2,4.904762,0.020833,0.571429,0.285714,5.211310,6533.142857,1332.000000
4,5,12284,81323,15,35,0,10,3,0.151052,0.428571,0.000000,0.300000,0.879623,1228.400000,8132.300000

### Higher the average means higher the credit Worthiness