In [27]:
import pandas as pd
import numpy as np

In [28]:
df = pd.read_csv('/Users/shivendragupta/Desktop/Machine Learning/Feature Engineering/health_data.csv')

In [29]:
df.head()

,Person_ID,Height_cm,Weight_kg,Waist_Circumference_cm,Hip_Circumference_cm,Body_Fat_Percentage
0,1,178,78,96,126,30.321620
1,2,191,116,64,83,17.051116
2,3,168,83,60,99,34.920655
3,4,154,70,99,89,26.344830
4,5,182,78,71,103,14.957262

# 1. Body Mass Index(BMI)

# BMI = Weight (kg) / (Height (m)²)

### BMI is a widely used indicator of overall body composition and health.

In [30]:
df['BMI'] = df['Weight_kg']/(df['Height_cm']/100)**2

df.head()

,Person_ID,Height_cm,Weight_kg,Waist_Circumference_cm,Hip_Circumference_cm,Body_Fat_Percentage,BMI
0,1,178,78,96,126,30.321620,24.618104
1,2,191,116,64,83,17.051116,31.797374
2,3,168,83,60,99,34.920655,29.407596
3,4,154,70,99,89,26.344830,29.515939
4,5,182,78,71,103,14.957262,23.547881

```Interpretation:

BMI < 18.5: Underweight

18.5 ≤ BMI < 24.9: Normal weight

25 ≤ BMI < 29.9: Overweight

BMI ≥ 30: Obese

# 2. Waist-to-Height Ratio (WHtR)

## WHtR = Waist Circumference (cm) / Height (cm)

### WHtR is another measure of abdominal obesity and is a better predictor of cardiovascular risk than BMI in some cases.

In [31]:
df['WHtR'] = df['Waist_Circumference_cm']/df['Height_cm']
df.head()

,Person_ID,Height_cm,Weight_kg,Waist_Circumference_cm,Hip_Circumference_cm,Body_Fat_Percentage,BMI,WHtR
0,1,178,78,96,126,30.321620,24.618104,0.539326
1,2,191,116,64,83,17.051116,31.797374,0.335079
2,3,168,83,60,99,34.920655,29.407596,0.357143
3,4,154,70,99,89,26.344830,29.515939,0.642857
4,5,182,78,71,103,14.957262,23.547881,0.390110

### WHtR > 0.5 indicates increased risk of cardiovascular diseases.

# 3. Lean Body Mass(LBM) Ratio

## LBM Ratio = Lean Body Mass / Total Body Weight

### Shows proportion of muscle & organs

In [32]:
body_fat_weight = df['Weight_kg'] - ((df['Weight_kg']*df['Body_Fat_Percentage'])/100)
lean_body_mass = df['Weight_kg'] - body_fat_weight
df['LBM_ratio'] = lean_body_mass/df['Weight_kg']
df.head()

,Person_ID,Height_cm,Weight_kg,Waist_Circumference_cm,Hip_Circumference_cm,Body_Fat_Percentage,BMI,WHtR,LBM_ratio
0,1,178,78,96,126,30.321620,24.618104,0.539326,0.303216
1,2,191,116,64,83,17.051116,31.797374,0.335079,0.170511
2,3,168,83,60,99,34.920655,29.407596,0.357143,0.349207
3,4,154,70,99,89,26.344830,29.515939,0.642857,0.263448
4,5,182,78,71,103,14.957262,23.547881,0.390110,0.149573

# 4. Fat-Free Mass Index (FFMI)

# FMI = (Weight * (1 - Body Fat Percentage)) / (Height²)

### Similar to BMI but adjusted for lean mass

In [33]:
df['FMI'] = (df['Weight_kg'] * (1 - (df['Body_Fat_Percentage'])/100)) / ((df['Height_cm']/100)**2)
df.head()

,Person_ID,Height_cm,Weight_kg,Waist_Circumference_cm,Hip_Circumference_cm,Body_Fat_Percentage,BMI,WHtR,LBM_ratio,FMI
0,1,178,78,96,126,30.321620,24.618104,0.539326,0.303216,17.153496
1,2,191,116,64,83,17.051116,31.797374,0.335079,0.170511,26.375567
2,3,168,83,60,99,34.920655,29.407596,0.357143,0.349207,19.138271
3,4,154,70,99,89,26.344830,29.515939,0.642857,0.263448,21.740015
4,5,182,78,71,103,14.957262,23.547881,0.390110,0.149573,20.025763

# 5. Visceral Fat Estimate

# Visceral Fat Estimate=Waist Circumference (cm)×Body Fat Percentage

### Visceral fat (fat around internal organs) is a strong predictor of cardiovascular disease. While direct measurement requires specialized equipment, you can estimate it using waist circumference and body fat percentage.

In [34]:
df['vis_fat'] = df['Waist_Circumference_cm']*df['Body_Fat_Percentage']/100
df.head()

,Person_ID,Height_cm,Weight_kg,Waist_Circumference_cm,Hip_Circumference_cm,Body_Fat_Percentage,BMI,WHtR,LBM_ratio,FMI,vis_fat
0,1,178,78,96,126,30.321620,24.618104,0.539326,0.303216,17.153496,29.108755
1,2,191,116,64,83,17.051116,31.797374,0.335079,0.170511,26.375567,10.912715
2,3,168,83,60,99,34.920655,29.407596,0.357143,0.349207,19.138271,20.952393
3,4,154,70,99,89,26.344830,29.515939,0.642857,0.263448,21.740015,26.081381
4,5,182,78,71,103,14.957262,23.547881,0.390110,0.149573,20.025763,10.619656