In [8]:
from sklearn.ensemble import BaggingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('/Users/shivendragupta/Desktop/Machine Learning/housing.csv',sep='\t',header=None)
df

                                                     0
0     0.00632  18.00   2.310  0  0.5380  6.5750  65...
1     0.02731   0.00   7.070  0  0.4690  6.4210  78...
2     0.02729   0.00   7.070  0  0.4690  7.1850  61...
3     0.03237   0.00   2.180  0  0.4580  6.9980  45...
4     0.06905   0.00   2.180  0  0.4580  7.1470  54...
..                                                 ...
501   0.06263   0.00  11.930  0  0.5730  6.5930  69...
502   0.04527   0.00  11.930  0  0.5730  6.1200  76...
503   0.06076   0.00  11.930  0  0.5730  6.9760  91...
504   0.10959   0.00  11.930  0  0.5730  6.7940  89...
505   0.04741   0.00  11.930  0  0.5730  6.0300  80...

[506 rows x 1 columns]

In [4]:
df = df[0].str.split(expand=True)

# Convert to numeric (optional but recommended)
df = df.apply(pd.to_numeric)

# Display the fixed DataFrame
print(df.head())

        0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7

       11    12    13
0  396.90  4.98  24.0
1  396.90  9.14  21.6
2  392.83  4.03  34.7
3  394.63  2.94  33.4
4  396.90  5.33  36.2

In [5]:
df.columns = ["CRIM", "ZN", "INDUS", "CHAS","NOX", "RM", "AGE", "DIS","RAD", "TAX", "PTRATIO", "B", "LSTAT", "MEDV"]

In [6]:
X = df.iloc[:,0:13]
y = df.iloc[:,-1]

In [7]:
X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.3,random_state=43)

In [12]:
lr = LinearRegression()
lr.fit(X_train,y_train)
r2_score(y_test,lr.predict(X_test))

0.6913275838214492

In [14]:
knr = KNeighborsRegressor()
knr.fit(X_train,y_train)
r2_score(y_test,knr.predict(X_test))

0.487382851989004

In [18]:
br = BaggingRegressor(n_estimators=500)

In [19]:
br.fit(X_train,y_train)

BaggingRegressor(n_estimators=500)

In [20]:
r2_score(y_test,br.predict(X_test))

0.8838831597889605

In [30]:
br1 = BaggingRegressor(estimator=LinearRegression(),n_estimators=100000)

In [31]:
br1.fit(X_train,y_train)

BaggingRegressor(estimator=LinearRegression(), n_estimators=100000)

In [32]:
r2_score(y_test,br1.predict(X_test))

0.6900874167933431

In [36]:
params = {'estimator': [None, LinearRegression(), KNeighborsRegressor()],
          'n_estimators': [20,50,100],
          'max_samples': [0.5,1.0],
          'max_features': [0.5,1.0],
          'bootstrap': [True, False],
          'bootstrap_features': [True, False]}

bagging_regressor_grid = GridSearchCV(BaggingRegressor(random_state=1, n_jobs=-1), param_grid =params, cv=3, n_jobs=-1, verbose=1)
bagging_regressor_grid.fit(X_train, y_train)

print('Train R^2 Score : %.3f'%bagging_regressor_grid.best_estimator_.score(X_train, y_train))
print('Test R^2 Score : %.3f'%bagging_regressor_grid.best_estimator_.score(X_test, y_test))
print('Best R^2 Score Through Grid Search : %.3f'%bagging_regressor_grid.best_score_)
print('Best Parameters : ',bagging_regressor_grid.best_params_)

Fitting 3 folds for each of 144 candidates, totalling 432 fits
Train R^2 Score : 1.000
Test R^2 Score : 0.858
Best R^2 Score Through Grid Search : 0.819
Best Parameters :  {'bootstrap': False, 'bootstrap_features': False, 'estimator': None, 'max_features': 0.5, 'max_samples': 1.0, 'n_estimators': 50}